In [21]:
import pandas as pd
import os

In [22]:
freedom = "Clean Data/CleanFreedom.csv"
suicide = "Clean Data/CleanSuicide.csv"
happiness = "Clean Data/CleanHappiness.csv"
fifa = "Clean Data/CleanFifa.csv"

In [23]:
freedom_pd = pd.read_csv(freedom)
suicide_pd = pd.read_csv(suicide)
happiness_pd = pd.read_csv(happiness)
fifa_pd = pd.read_csv(fifa)

In [31]:
fifa_pd_col = fifa_pd[['rank','country_full','total_points']]
fifa_pd_col.columns = ['rank', 'Country','Total Points']
fifa_pd_col

     rank                   Country  Total Points
0       1                 Argentina       1634.02
1       2                    Brazil       1544.05
2       3                   Germany       1432.54
3       4                     Chile       1403.96
4       5                   Belgium       1367.77
5       6                  Colombia       1344.70
6       7                    France       1305.41
7       8                  Portugal       1229.12
8       9                   Uruguay       1187.31
9      10                     Spain       1165.66
10     11               Switzerland       1128.75
11     12                     Wales       1120.86
12     13                   England       1114.45
13     14                   Croatia       1103.27
14     15                    Poland       1086.72
15     16                     Italy       1082.60
16     17                Costa Rica       1040.55
17     18                    Mexico       1012.00
18     19                      Peru        965.37
19     20                   Ecuador        890.45
20     21                   Iceland        889.28
21     22               Netherlands        887.14
22     23       Republic of Ireland        857.64
23     24                    Turkey        850.58
24     25                  Slovakia        837.07
25     26                   Hungary        826.32
26     27    Bosnia and Herzegovina        825.47
27     28                       USA        822.00
28     29                   IR Iran        814.49
29     30                   Ukraine        803.65
..    ...                       ...           ...
181   182                      Guam         88.99
182   183                     Malta         85.13
183   184                     Macau         81.86
184   185                Bangladesh         80.79
185   186                Seychelles         77.67
186   187                   Bermuda         76.96
187   187           Solomon Islands         76.50
188   189             Liechtenstein         75.27
189   190         Brunei Darussalam         74.38
190   191               Timor-Leste         64.00
191   191            American Samoa         63.75
192   191              Cook Islands         63.75
193   191                     Samoa         63.75
194   195                 Sri Lanka         44.14
195   195         US Virgin Islands         43.99
196   197                  Pakistan         39.64
197   198                  Mongolia         38.30
198   199                Montserrat         30.42
199   200            Cayman Islands         21.25
200   201  Turks and Caicos Islands         19.80
201   202                San Marino         16.63
202   203                   Andorra         11.68
203   204    British Virgin Islands         10.62
204   205                  Anguilla          0.00
205   205                   Bahamas          0.00
206   205                  Djibouti          0.00
207   205                   Eritrea          0.00
208   205                 Gibraltar          0.00
209   205                   Somalia          0.00
210   205                     Tonga          0.00

[211 rows x 3 columns]

In [47]:
freedom_suicide_pd = pd.merge(freedom_pd,suicide_pd, on='Country', how='inner')
happiness_freedom_suicide_pd = pd.merge(freedom_suicide_pd, happiness_pd, on='Country', how='inner')
happiness_freedom_suicide_pd.columns = ['Country', 'Freedom Score', 'Freedom Rank', 'Suicide Rate per 100k', 'Happiness Rank','Happiness Score']
happiness_freedom_suicide_fifa = pd.merge(happiness_freedom_suicide_pd, fifa_pd_col, on='Country',how='inner')
happiness_freedom_suicide_fifa.columns = ['Country', 'Freedom Score', 'Freedom Rank', 'Suicide Rate per 100k', 'Happiness Rank','Happiness Score', 'Fifa Rank','Fifa Total Points']
happiness_freedom_suicide_fifa.to_csv('Clean Data/CleanMerged.csv')